### ISSUE TITLE
The file istio-envoy-filter-jwt-lua.yaml must be modified to take into account the depreciation of certain parameters

### ISSUE THREAD

**Issue by ealcyon** [BarDweller/istio-content-based-routing#1]
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: jwt-lua-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
       name: envoy.lua
       typed_config:
         "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
         inlineCode: |
```
#### The rest of the code, below inlineCode, is unchanged  ####
